### PR TITLE
ppdiffusers add controlnet_sd3

### PR DESCRIPTION
**Pull request by javey-q**
- add controlnet_sd3.py
- add pipeline_stable_diffusion_3_controlnet.py
- add pipeline_stable_diffusion_3_controlnet_inpainting.py
- modify transformer_sd3.py for controlnet residual

### CODE REVIEW

**Comment by westfish** [comment]
增加一个推理吧：ppdiffusers/examples/inference/text_to_image_generation-stable_diffusion_3_controlnet.py，参考text_to_image_generation-stable_diffusion_controlnet.py

**Comment by westfish** [comment]
还需要增加SD3MultiControlNetModel

**Comment by westfish** [comment]
增加一下Dummy Classes吧ppdiffusers/ppdiffusers/utils/dummy_paddle_and_paddlenlp_objects.py

**Comment by westfish** [comment]
补充一下单测：tests/pipelines/controlnet_sd3/test_controlnet_sd3.py

**Comment by javey-q** [comment]
> 增加一下Dummy Classes吧ppdiffusers/ppdiffusers/utils/dummy_paddle_and_paddlenlp_objects.py

**Pull request closed without merging**
